{
  "name": "${appName}",
  "private": true,
  "devDependencies": {
    "cross-env": "^3.1.1",
    "react-scripts": "0.7.0",
    "react-test-renderer": "^15.3.2",
    "redux-devtools-extension": "^1.0.0",
    "steiner-cli": "^0.10.0"
  },
  "dependencies": {
    "axios": "^0.15.0",
    "mousetrap": "^1.6.0",
    "query-string": "^4.2.3",
    "rc-pagination": "^1.5.5",
    "rc-tooltip": "^3.4.2",
    "react": "^15.3.2",
    "react-addons-css-transition-group": "^15.3.2",
    "react-addons-shallow-compare": "^15.3.2",
    "react-dom": "^15.3.2",
    "react-helmet": "^3.1.0",
    "react-highlighter": "^0.3.3",
    "react-modal": "^1.5.2",
    "react-redux": "^5.0.0-beta.3",
    "react-redux-loading-bar": "^2.4.0",
    "react-router": "^4.0.0-alpha.5",
    "react-router-addons-controlled": "^0.0.1",
    "react-select": "^1.0.0-rc.2",
    "react-sidebar": "^2.2.1",
    "react-virtualized": "^8.0.11",
    "reapop": "^0.6.0",
    "reapop-theme-wybo": "^0.4.0",
    "redux": "^3.6.0",
    "redux-batched-subscribe": "^0.1.6",
    "redux-form": "^6.0.5",
    "redux-localstorage": "^0.4.1",
    "redux-logger": "^2.6.1",
    "redux-saga": "^0.12.0",
    "redux-thunk": "^2.1.0",
    "reflexbox": "^2.2.2",
    "revalidate": "^0.4.1",
    "seamless-immutable": "^6.1.3",
    "steiner": "^0.10.0",
    "vivi": "^0.4.0"
  },
  "scripts": {
    "start:plain": "react-scripts start",
    "build:plain": "react-scripts build",
    "test:plain": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "start": "cross-env NODE_PATH=./src npm run start:plain",
    "build": "cross-env NODE_PATH=./src npm run build:plain",
    "test": "cross-env NODE_PATH=./src npm run test:plain"
  }
}
